name: Push Develop Branch
on:
  push:
    branches:
      - develop
jobs:
  Notify_Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: develop ブランチにマージされました。develop ブランチを pull してください。コマンドは git pull origin develop です。
          mention: "channel"
          if_mention: always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
